Update plot_geotiff_imshow.py
An osgeo import?

When I run this I get:- 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9bc3a0f63f7a> in <module>
      5 from pyproj import Proj, transform
      6 
----> 7 from mtpy.modeling.modem import Model, Data
      8 from mtpy.utils import gis_tools
      9 

~\AppData\Local\Continuum\anaconda3\envs\gempy2021\lib\site-packages\mtpy\modeling\modem\__init__.py in <module>
     15 # from mtpy.imaging.plot_depth_slice import PlotDepthSlice     # can cause circular import error
     16 from .plot_slices import PlotSlices
---> 17 from .plot_rms_maps import PlotRMSMaps
     18 from .phase_tensor_maps import PlotPTMaps
     19 

~\AppData\Local\Continuum\anaconda3\envs\gempy2021\lib\site-packages\mtpy\modeling\modem\plot_rms_maps.py in <module>
     27 
     28 from mtpy.utils import basemap_tools
---> 29 from mtpy.utils.plot_geotiff_imshow import plot_geotiff_on_axes
     30 from mtpy.utils.mtpylog import MtPyLog
     31 from mtpy.utils.gis_tools import epsg_project

~\AppData\Local\Continuum\anaconda3\envs\gempy2021\lib\site-packages\mtpy\utils\plot_geotiff_imshow.py in <module>
     16 import numpy as np
     17 from osgeo import gdal, osr, ogr
---> 18 from gdalconst import GA_ReadOnly
     19 #from osgeo.gdalconst import GA_ReadOnly
     20 

ModuleNotFoundError: No module named 'gdalconst'

making it osgeo.gdalconst appears to work